---
title: "TP3: Una masacre estadística (WIP)"
practica: "Trabajo Práctico 3"
---

## Introducción

Como si la riqueza del idioma español no fuera suficiente, 
muy frecuentemente los argentinos recurrimos a palabras o expresiones que, sin contexto, 
carecen de significado o transmiten algo completamente distinto al uso que les damos.

Si de palabras se trata, sobran los ejemplos: perro, bife, mango, cana, puchero, 
panqueque, pavo, chorro, bondi y rata son algunos de ellos. Tampoco escasean frases que, 
inevitablemente, confunden a los que nunca han pisado suelo argento: tomar el palo,
hacer la cama, mandar fruta, comer vidrio, estar en pañales, pararse de manos o sacar el 
cuero.

El presente trabajo práctico gira alrededor de una palabra clave: masacre. 
La palabra "masacre" se utiliza, generalmente, para referirse a la matanza violenta e 
indiscriminada de un gran número de personas. Sin embargo, y siguiendo la línea de los 
párrafos introductorios, no la vamos a usar por su significado más obvio, aunque sí por 
uno muy cercano.


## El caso 🕵️‍♀️

Comenzar una carrera en estadística puede llevarnos a lugares impensados (algunos dirán 
que se converge, casi seguramente, a un estado de máxima confusión). Quien puede dar 
prueba de esto es Guido, un estudiante de estadística que, habiendo siendo fanático de
[_CSI: Crime Scene Investigations_](https://es.wikipedia.org/wiki/CSI:_Crime_Scene_Investigation), 
nunca imaginó que iba a cumplir su sueño de formar parte la policía científica de Córdoba.

Pero no todo es color de rosas en el camino de Guido. Al poco tiempo de instalado en 
la capital del cuarteto, una madrugada de miércoles, su unidad de trabajo fue convocada
de manera urgente por el comisario de Salsipuedes para investigar una crimen que, 
aparentemente, había sido recién cometido.

¡Qué masacre! Fue lo único que pudo a decir al llegar al lugar. 
El caos se extendía por toda la habitación.
Muebles volcados y destrozados. Utensillos de cocina desparramados y manchados. 
La brisa matutina se abría paso por los vidrios estallados y la débil luz de los móviles
policiales dejaban ver que el cuerpo de Sergio Contreras yacía en un charco de sangre
hacia un extremo del salón.

Abundan las tareas que los investigadores deben realizar en un crimen de estas 
características. Nuestro protagonista, Guido, quedó encargado de determinar la hora 
en que se produjo la muerte. En un marco tan desolador, Guido se alegró de encontrarse,
al fin, frente a un caso de aplicación basado en datos reales.

## La metodología 📚

La medicina forense dispone de un gran abanico de métodos para estimar la hora del 
fallecimiento. Estos estudian diferentes características, como por ejemplo la rigidez 
corporal, la presencia de livideces (manchas en el cuerpo), el nivel de descomposición, 
etc. 

Una de las estrategias más utilizadas se basa en el estudio de la temperatura corporal.
Durante las primeras horas después de la muerte ocurre el enfriamiento del cuerpo,
que se conoce como enfriamiento postmortem o _algor mortis_. 

<!-- Para entender como utilizar la temperatura para determinar la hora de muerte, primero 
necesitamos entender cómo varia la temperatura de un cuerpo en función del tiempo 
transcurrido. -->

La temperatura es una medida del grado de agitación de las partículas de un cuerpo. 
Un sólido (o líquido, o gas) está _más caliente_ que otro si sus partículas tienen 
(en promedio) mayor grado de agitación. Sabemos por evidencia empírica que si un cuerpo se
pone en contacto con otro que tiene una temperatura menor, hay una transferencia de 
energía que hace que el primero se enfríe y el segundo se caliente, hasta que alcanzan el 
denominado equilibrio térmico.

De manera similar, esto es lo que ocurre con el cuerpo de Sergio que yace en el living
de su casa: en algún momento, llega al equilibrio térmico con el ambiente. 
La salvedad necesaria acá es que, como el ambiente es grande, no aumenta su temperatura 
con la energía que pierde el cuerpo.

Ahora bien, el ritmo con el cual el cuerpo pierde energía no es constante. 
Físicamente, mientras mayor sea la diferencia de temperatura entre dos cuerpos, más rápido
fluirá la energía (y más rápido cambiará la temperatura). Si estudiamos la temperatura de
un cuerpo en función del tiempo, notaremos que el ritmo con el que cambia decrece a
medida con el que transcurre el tiempo.

La lectura del párrafo anterior debería permitir asociar el concepto de _ritmo de cambio_ 
con la noción matemática de derivada. En efecto, la derivada de la temperatura respecto al
tiempo varía con el tiempo. En otras palabras, la pendiente no es constante.

Las leyes que rigen el universo pueden muchas veces formularse en términos de lo que en 
matemática se conoce como ecuación diferencial. En este caso, la temperatura del cuerpo
de Segio satisface la siguiente ley:

$$
\frac{\mathrm{d}T(t)}{\mathrm{d}t} = r [T_{\text{amb}} - T(t)]
$$

donde $T_{\text{amb}}$ es la temperatura ambiente (un valor fijo y conocido), $r$ es una 
constante y $T(t)$ es la función (en principio desconocida) que describe la temperatura 
del cuerpo en función del tiempo.

No se trata de una ecuación algebraica donde la solución es un valor numérico sino de una 
ecuación donde la solución es una función. Buscamos una función $T(t)$ que satisfaga la 
ecuación: su derivada debe cambiar con el valor que toma la función.

Una función que satisface esa ecuación es:

$$
T(t) = T_{\text{amb}} + (T_i - T_{\text{amb}})e^{-rt}
$$ 

siendo $T_i$ la temperatura a la que está inicialmente el cuerpo de Sergio.

## Bayes al rescate 🎲

Es ahora cuando entran en escena nuevos e impensados protagonistas: los estudiantes
de la materia Estadística Bayesiana. Utilizando los conocimientos adquiridos a lo largo 
del curso y la información relevante volcada en este documento, deberán hacer el trabajo
originalmente encomendado a Guido: determinar la hora de muerte de Sergio.

1.  Verifique que la función anterior satisface la ecuación diferencial.
2.  Grafique $T(t)$ para $T_{\text{amb}} = 23 \text{ C°}$ y $T_i = 37 \text{ C°}$, 
    para dos valores de $r$, $r_1 = 0.1$ y $r_2 = 0.3$. ¿Qué representa $r$?
3.  ¿Cuál es un valor realista de $r$? De ser necesario, busque información acerca de los 
tiempos del enfriamiento postmortem.

Téngase presente el siguiente resumen de los hechos ocurridos:

* 5:33 hs - El Centro de Atención de Emergencias 911 recibe un llamado de Lidia Benegas, 
alertando sobre ruidos extraños en la vivienda de su vecino en la localidad de Salsipuedes.
Agrega que le llama la atención observar que las puertas y ventanas estuvieran abiertas
tan temprano.
* 5:36 hs - La policía de Salsipuedes recibe el llamado y envía un móvil a la dirección 
indicada.
* 5:52 hs - Llega el móvil policial a destino, y ante la ausencia de respuesta, 
deciden ingresar a la casa y realizar una inspección ocular.
* 6:00 hs - Concluida la inspección, se constata la presencia de una persona tendida
en el suelo, aparentemente muerta, y se llama a la policía científica de Córdoba para 
actuar en el lugar.
* 6:45 hs - Arriba la policía científica al lugar. El médico forense determina la 
ausencia de signos vitales. El informe menciona una temperatura corporal de **XX** °C.
* 6:50 hs - Comienza el relevamiento de pruebas. Miembros del equipo forense toman 
fotografías, recogen huellas dactilares, y secuestran elementos que puedan aportar a la 
causa.
* 8:15 hs - Finalizados los procedimientos legales y técnicos, se procede a colocar el
cuerpo en la bolsa de óbito para su posterior traslado a morgue judicial. 
El termómetro registra que la temperatura del cadáver es de **YY** °C.
* 8:40 hs - Comienza el traslado del cuerpo a morgue judicial en Córdoba Capital.
* 9:55 hs - Llega a destino la unidad de traslado y se resguarda el cuerpo a espera de su 
correspondiente autopsia.
* 13:30 hs - Comienza la autopsia. El cadáver se encuentra a **ZZ** °C.
* 16:10 hs - Finaliza la autopsia, se determina que Sergio falleció desangrado producto 
de una herida punzante recibida en el bazo.

Para simplificar la construcción de un modelo, en lugar de considerar la temperatura del 
cuerpo, se considerará la diferencia entre la temperatura del cuerpo y la 
temperatura ambiente $T - T_{\text{amb}}$. Además, se llamará $T_{\text{diff}}$ a la 
diferencia entre la temperatura inicial del cuerpo y la temperatura ambiente 
$T_i - T_{\text{amb}}$.

$$
T(t) - T_{\text{amb}} = T_{\text{diff}} e^{-rt}
$$

4.  Verifique que el logaritmo natural de la nueva variable $T(t) - T_{\text{amb}}$ es 
    una función lineal de $t$. ¿Qué representan el intercepto y la pendiente? Llámelos 
    $\beta_0$ y $\beta_1$.

Se propone ajustar un modelo lineal normal utilizando los datos transformados.

5.  En función del enunciado del problema y de su conocimiento, elija una distribución
     _a priori_ para $\beta_0$, $\beta_1$ y $\sigma$. 
    ¿Cuáles son las implicancias de sus distribuciones _a priori_? 
    Realice pruebas predictivas _a priori_.
    Considere una temperatura ambiente de 22 °C.
6.  ¿Es posible estimar la hora de muerte utilizando la información disponible hasta las 
        7 de la mañana? En caso afirmativo, explicite los supuestos realizados y ajuste 
        el modelo usando Stan.
7.  Luego, estime la hora de muerte utilizando la información disponible hasta las 10 horas. 
8.  Finalmente, estime la hora de muerte utilizando todas las mediciones de temperatura
    realizadas sobre el cuerpo de Sergio. Compare esta estimación con la obtenida en el 
    punto **7**. ¿Cuál de las dos es un reflejo más fiel de la verdadera hora de muerte?
    Justifique su respuesta.
9. ¿Modificaría algún aspecto del modelo si supiera que Sergio no gozaba de buena salud
al momento de fallecer?


<!-- 7.  Encontrar el _posterior_ de $r$, de $T_{\text{diff}}$ y de la temperatura inicial del 
    agua $T_i$. -->
<!-- 8.  Predecir la temperatura a la que estará el agua transcurridas 12:00 h del inicio de 
    la experiencia. -->

<!-- Bondi, Perro, Rata, Gato, Cana Mango, Ñoqui, Botón, Chorro, Gamba, Banana, Bife, Panqueque, Pavo, Picada, Puchero, Llantas -->
<!-- Tomar el palo, Estar en pañales, Abrir el paraguas, Chupar medias, Hacer la cama, Mandar fruta, Comer vidrio, Pararse de manos, Vender humo, Sacar el cuero -->