---
title: "Práctica - U2"
---

# Modelos de Distribuciones Conjugadas

1. Ejercicio 1

# Simulaciones

1.  `Modern Data Science with R` El tiempo que un empleado de recursos humanos demora en hacer una entrevista tiene distribución exponencial con media 30 minutos. Los tiempos de duración de cada entrevista se pueden considerar independientes entre sí. Las entrevistas a postulantes para un trabajo están programadas cada 15 minutos, comenzando desde las 8. Es válido considerar que todos los postulantes llegan puntuales a su entrevista. Cuando la persona del turno de las 8:15 llega a la oficina

    i.  ¿Cuál es la probabilidad de que tenga que esperar antes de ser entrevistada?
    ii. ¿Cuál es el horario esperado al que terminará su entrevista?

2.  Dos personas se conocen en la fila de embarque para un vuelo en un avión Airbus A330-300

    i.  ¿Cuál es la probabilidad de que tengan asientos en la misma fila?
    ii. ¿Cuál es la probabilidad de que estén sentados en asientos adyacentes?

3.  `Modern Data Science with R` El Problema de Monty Hall es trabajado con frecuencia en cursos de Probabilidad. Mediante simulación, determine cuál es la probabilidad de ganar el juego si se cambia de puerta.

4.  Basándose en el [siguiente tuit](https://twitter.com/Kit_Yates_Maths/status/1542767039814713346) y conociendo el problema del cumpleaños (¿cuántas personas debe haber en una habitación para que la probabilidad de que dos de ellas cumplan años el mismo día sea mayor a X%?) construir un gráfico similar al del tuit donde se grafique la probabilidad de que haya $n$ personas que cumplan años el mismo día para $K$ personas presentes en la habitación.

5.  El álbum oficial del Mundial de Fútbol de Qatar 2022 consta de 638 figuritas. Cada paquete trae cinco figuritas.

    i. Comprando cinco paquetes, ¿cuál es la probabilidad de tener a Messi?
    ii. Comprando cinco paquetes, ¿cuál es la probabilidad de sacar a Messi repetido?
    iii. ¿Cuántos paquetes se necesitan, en promedio, para completar el álbum?
    iv. Si a una persona le faltan diez figuritas para completar el álbum, ¿cuántos paquetes tiene que comprar para asegurarse de lograrlo?

6. Si se arroja una moneda $n$ veces, ¿cuál es la probabilidad de que no haya secuencias de $k$ caras?

7. ¿Cuál es la probabilidad de que tres personas en un ascensor con doce pisos presionen vayan a tres pisos consecutivos?

8. Previo a la final de la Copa América 2021, los jugadores de la Selección Argentina se reúnen en la habitación del hotel como se describe en [este tuit](https://twitter.com/PlanetaDeCABJ/status/1587925636869300224).
    
    i. ¿Cuál es la probabilidad de que un jugador adivine una de diez cartas?
    ii. ¿Cuál es la probabilidad de que tres de ellos adivinen una de diez cartas?

10.  Quizás algo con tasa de falsos descubrimientos, p-values y su distribución...
