# Distribuciones de probabilidad

## Normal

$$
X \sim \text{Normal}(\mu, \sigma)
$$

$$
p(x \mid \mu, \sigma) = \frac{1}{\sqrt{2\pi} \sigma}e^{-\frac{(x - \mu) ^ 2}{2\sigma^2}}
$$

$$
P(X \le x) = \int_{-\infty}^{x}{p(x | \mu, \sigma) dx}
$$

o también

$$
P(X \le x) = \frac{1}{2} \left[1 + \text{erf}\left(\frac{x - \mu}{\sigma\sqrt{2}} \right) \right]
$$

con

$$
\text{erf}(x) = \frac{2}{\sqrt{\pi}}\int_0^{x} {e^{-t^2}dt}
$$

* $X \in \mathbb{R}$
* $\mu \in \mathbb{R}$
* $\sigma > 0$
* $\mathbb{E}(X) = \mu$
* $\mathbb{V}(X) = \sigma^2$


## T-Student


$$
X \sim \text{StudentT}(\nu)
$$

$$
p(x \mid \nu) =
    \frac{\Gamma(\frac{\nu + 1}{2})}{\Gamma(\frac{\nu}{2})}
    \left(\frac{1}{\pi\nu}\right) ^ {\frac{1}{2}}
    \left[1 + \frac{x^2}{\nu}\right]^{-\frac{\nu + 1}{2}}
$$

$$
P(X \le x) = \frac{1}{2} + x \Gamma\left(\frac{\nu + 1}{2}\right) 
             \frac{{}_2F_1\left(\frac{1}{2}, \frac{v + 1}{2}, \frac{3}{2}, \frac{-x^2}{\nu} \right)}
             {\sqrt{\pi \nu} \Gamma(\frac{\nu}{2})}
$$


donde ${}_2F_1$ es la [función hipergeométrica](https://es.wikipedia.org/wiki/Funci%C3%B3n_hipergeom%C3%A9trica).


* $X \in \mathbb{R}$
* $\nu > 0$
* $\mathbb{E}(X) = 0$ si $\nu > 1$
* $\mathbb{V}(X) = \nu / (\nu - 2)$ si $\nu > 2$

## Gamma

### Parametrización 1

$$
X \sim \text{Gamma}(k, \theta)
$$

$$
p(x \mid k, \theta) = \frac{1}{\Gamma(k)\theta^k}x^{k-1}e^{-\frac{x}{\theta}}
$$

$$
P(X \le x) = \frac{1}{\Gamma(k)} \gamma \left(k, \frac{x}{\theta}\right)
$$

* $X > 0$
* $k > 0$
* $\theta > 0$
* $\mathbb{E}(X) = k\theta$
* $\mathbb{V}(X) = k\theta^2$

### Parametrización 2

$$
X \sim \text{Gamma}(\alpha, \beta)
$$


$$
p(x | \alpha, \beta) = \frac{1}{\Gamma(\alpha)}x^{\alpha-1}e^{-\beta x}\beta^\alpha
$$

$$
P(X \le x) = \frac{1}{\Gamma(\alpha)} \gamma(\alpha, \beta x)
$$

* $X > 0$
* $\alpha > 0$
* $\beta > 0$
* $\mathbb{E}(X) = \alpha/\beta$
* $\mathbb{V}(X) = \alpha/\beta^2$

## Exponencial

$$
X \sim \text{Exponencial}(\lambda)
$$

$$
p(x \mid \lambda) = \lambda e^{-\lambda x}
$$

$$
P(X \le x) = 1 - e^{-\lambda x}
$$


* $X > 0$
* $\lambda > 0$
* $\mathbb{E}(X) = 1 / \lambda$
* $\mathbb{V}(X) = 1 / \lambda ^ 2$

Es un caso particular de $\text{Gamma}(\alpha, \beta)$ con $\alpha = 1$ y $\beta = \lambda$

## Beta

$$
X \sim \text{Beta}(a, b)
$$

$$
p(x \mid a, b) = \frac{x^{a-1} (1-x)^{b-1}}{B(a, b)}
$$

$$
B(a, b) = \int_0^1 x^{a-1} (1-x)^{b-1} dx = \frac{\Gamma(a)\Gamma(b)}{\Gamma(a+b)}
$$

$$
\Gamma(x) = \int_0^\infty u^{x-1} e^{-u} du
$$

* $X \in (0, 1)$
* $\displaystyle \mathbb{E}(X) = \frac{a}{a + b}$
* $\displaystyle \mathbb{V}(X) = \frac{ab}{(a + b) ^ 2 (a + b + 1)}$

## Binomial

$$
X \sim \text{Binomial}(\theta, n)
$$

$$
p(x \mid \theta, n) = {n \choose x} \theta^x (1 - \theta)^{(n - x)}
$$

$$
P(X \le x) = \sum_{i = 0} ^ {x} {n \choose i} \theta^i (1 - \theta)^{(n - i)}
$$


* $X \in \{0, 1, 2, \cdots, n\}$
* $\theta \in [0, 1]$
* $n \in \{0, 1, 2, \cdots \}$
* $\mathbb{E}(X) = n \theta$
* $\mathbb{V}(X) = n \theta (1 - \theta)$

## Poisson

$$
X \sim \text{Poisson}(\lambda)
$$

$$
p(x \mid \lambda) = \frac{\lambda^x e^{-\lambda}}{x!}
$$

$$
P(X \le x) = e^{-\lambda} \sum_{i = 0} ^ {x} \frac{\lambda^i}{i!}
$$

* $X \in \{0, 1, 2, \cdots\}$
* $\lambda > 0$
* $\mathbb{E}(X) = \lambda$
* $\mathbb{V}(X) = \lambda$

## Binomial Negativa

$$
X \sim \text{BinomialNegativa}(r, p)
$$

$$
p(x \mid k, p)= \binom{x + r - 1}{x}(1 - p)^x p^r
$$

* $X \in \{0, 1, 2, \cdots \}$
* $r \in \{1, 2, 3, \cdots \}$
* $p \in [0, 1]$
* $\mathbb{E}(X) = r(1 - p) / p$
* $\mathbb{V}(X) = r(1 - p) / p^2$


<!-- 
## Student T
-->