---
title: Calendario
bibliography: ../references.bib
tbl-colwidths: [2.5, 10, 5, 27.5, 5, 25, 25]
page-layout: full
css: calendar.css
---

```{r}
#| echo: false
#| include: false
library(stringr)
paste_human <- function(x, sep = ", ", last = " y ") {
  x_length <- length(x)
  if (x_length > 1) {
    output <- paste(x[1:(x_length - 1)], collapse = sep)
    output <- paste(c(output, x[[x_length]]), collapse = last)
  } else {
    output <- paste(x)
  }
  return(output)
}

format_date <- function(date, format, locale = NULL) {
  if (!is.null(locale)) {
    original_locale <- Sys.getlocale("LC_TIME")
    Sys.setlocale("LC_TIME", locale)
    on.exit(Sys.setlocale("LC_TIME", original_locale))
  }
  return(format(as.Date(date), format))
}
```

```{r}
#| echo: false
#| include: false
SHEET_ID <- "1lEmhEuxPychZjZOJLnkKYc0e7ZKPrKxdQdkw1XioHzo"
googlesheets4::gs4_deauth()
data <- googlesheets4::read_sheet(SHEET_ID)
data[["fecha"]] <- as.Date(data[["fecha"]])
data$unidad <- sapply(data$unidad, function(x) if (is.null(x)) return(NA) else return(x))
data[] <- lapply(data, as.character)
data[] <- lapply(data, function(x) gsub("\n", "<br>", x))

# Parsear las citas recomendadas y mostrarlas de una manera mas amigable
data$lectura <- str_split(data$lectura, ",") |>
  lapply(str_trim) |>
  lapply(str_split, pattern = "-") |>
  lapply(
    function(entries) {
      output_list <- list()
      for (entry in entries) {
        name <- entry[1]
        value <- entry[2]
        if (name %in% names(output_list)) {
          output_list[[name]] <- c(output_list[[name]], value)
        } else {
          output_list[[name]] <- value
        }
      }
      output_vector <- character(length(output_list))
      output_names <- names(output_list)
      if (length(output_names) == 1 && is.na(output_names)) return(output_vector)

      for (i in seq_along(output_list)) {
        book <- output_names[i]
        chapters <- sort(str_trim(str_replace_all(output_list[[book]], "[a-zA-Z]", "")))

        if (length(chapters) > 1) {
          value <- paste0(book, ": ", paste("Capítulos", paste_human(chapters)))
        } else {
          value <- paste0(book, ": ", paste("Capítulo", chapters))
        }
        output_vector[i] <- value
      }
      return(output_vector)
    }
  ) |>
  vapply(
    function(entry) {
      if (length(entry) == 1 && entry == "") {
        return(entry)
      } else {
        return(paste("•", entry, collapse = "<br>"))
        # No funciona. Creo que tiene que ver con 
        # https://github.com/quarto-dev/quarto-cli/issues/4419
        # paste(
        #   "<ul>",
        #   paste("<li>", entry, "</li>", collapse = " "),
        #   "</ul>"
        # )
      }
    },
    character(1)
  )


data$tema <- str_replace_all(data$tema, "(\\n)|(<br>)", " ") |>
  str_replace_all("\\.\\s*", ".") |>
  str_split("\\.") |>
  vapply(
    function(x) {
      if (length(x) == 1 && is.na(x)) {
        return(x)  
      } else {
        # Solo las cadenas no vacias
        return(paste("•", str_trim(x[x != ""]), collapse = "<br>"))
      }
    },
    character(1)
  )
data$novedades <- str_replace_all(data$novedades, "\\|", "<br>")
# %e no se queda con el leading zero que conserva %d
# Los meses van en minuscula... sorpresa
data$fecha <- format_date(data$fecha, "%e de %B", "es_AR.utf8")
```

```{r, echo=FALSE}
enquote <- function(x) {paste0("'", x, "'")}

add_pdf_link <- function(link) {
    is_active <- !is.na(link)
    if (is_active) {
        code <- paste0(
            paste0("<a href=", enquote(link), ">"),
            "<i class='fas fa-file-pdf fa-fw active'></i></a>"
        )
    } else {
        code <- "<i class='fas fa-file-pdf fa-fw inactive'></i>"
    }
    return(code)
}

data[["apuntes"]] <- sapply(data[["apuntes"]], add_pdf_link)
data[is.na(data)] <- ""
```

```{r echo=FALSE}
knitr::kable(
    data,
    col.names = c(
        "Semana", "Fecha", "Unidad", "Temas", "Apunte", "Lectura sugerida", "Otras actividades"
    ),
    align = c("c", "c", "c", "l", "c", "l", "l"),
    escape = FALSE
)
```

{{< fa pdf >}}

