---
title: Programa
---

# Fundamentación

La Estadística Bayesiana es un enfoque de la inferencia estadística que se basa en utilizar probabilidades para representar el conocimiento disponible sobre el conjunto de parámetros de un modelo y actualizar esa información utilizando la Regla de Bayes a partir de la observación de un conjunto de datos. El conocimiento inicial se representa con una distribución de probabilidad a priori, la información contenida en los datos observados se modeliza con una función de verosimilitud y ambas fuentes de información se combinan para obtener una distribución de probabilidad a posteriori. La información a posteriori puede ser utilizada para extraer conclusiones sobre el fenómeno en estudio y realizar predicciones sobre datos no observados o eventos futuros.

Los métodos bayesianos requieren, salvo en casos muy simples, una complejidad computacional que resultaba inalcanzable hace algunos años. Gracias a desarrollos revolucionarios en el ámbito de la computación, la principal barrera para la implementación de los modelos bayesianos desapareció y la utilización de estos se ha incrementado masivamente en múltiples campos científicos. Esta creciente popularidad se debe a que la inferencia bayesiana brinda un marco teórico consistente que permite la incorporación de información a priori, el desarrollo de un aprendizaje secuencial, la obtención de inferencias y predicciones en forma de distribuciones de probabilidad, el tratamiento de datos faltantes, los análisis con pocos datos, entre otras ventajas.

# Objetivos

Que quienes cursen la materia logren:

-   entender las características y los conceptos fundamentales de la Estadística Bayesiana;
-   describir las características principales de la Estadística Bayesiana;
-   comprender la complejidad analítica de la inferencia bayesiana y la necesidad de la utilización de un enfoque computacional para superar estas dificultades;
-   ser capaces de aplicar métodos bayesianos a problemas reales utilizando software específico; e
-   interpretar los resultados del proceso de análisis bayesiano de datos.

# Contenidos

Unidad 1: Introducción y Fundamentos de la Estadística Bayesiana

:   Probabilidad para cuantificar la incertidumbre. Modelos de probabilidad. Regla de Bayes. Inferencia bayesiana. Distribución a priori, función de verosimilitud, distribución a posteriori.

Unidad 2: Inferencia Bayesiana

:   Modelos de distribuciones conjugadas. Modelos de un parámetro. Modelo beta-binomial. Enfoque intuitivo. Distribución a posteriori como compromiso entre la verosimilitud y la distribución a priori. Razonamiento secuencial. Modelo normal-normal. Modelo gamma--Poisson. Modelos de varios parámetros. Modelo normal -- normal-gamma-inversa. Modelo Dirichlet--multinomial.

    Elección de distribuciones a priori: no informativas (impropias, de Jeffrey) y débilmente informativas. Medidas de resumen de la distribución a posteriori. Intervalos de credibilidad. Distribución predictiva a posteriori. Nociones de teoría de la decisión bayesiana. Riesgo bayesiano. Estimador de Bayes.

Unidad 3: Métodos Computacionales

:   Limitaciones del enfoque analítico: cálculo de probabilidades y determinación de la distribución a posteriori. Soluciones: análisis de datos simulados y aproximación de grilla. Introducción al cómputo bayesiano. Nociones básicas de métodos de cadenas de Markov -- Montecarlo (MCMC). Algoritmo de Metropolis--Hastings. Montecarlo Hamiltoniano. Diagnóstico de métodos MCMC.

    Programación probabilística. Alternativas. Sintaxis de modelos. Ejemplos. Diagnóstico. Medidas de resumen a partir de las cadenas obtenidas. Visualizaciones.

Unidad 4: Modelos Lineales

:   Modelos lineales. Elección de distribuciones a priori. Regularización. Diagnóstico de modelos. Predicciones basadas en distribuciones de probabilidad. Pruebas predictivas a priori y a posteriori. Densidad predictiva a posteriori logarítmica evaluada punto a punto (lppd). Deviance. Criterios de información: AIC, BIC, WAIC. Validacion cruzada. Sobreajuste y subajuste. Validación cruzada utilizando muestreo por importancia mediante suavizado Pareto (PSIS-CV).

Unidad 5: Modelos Avanzados

:   Regresión logística. Regresión Poisson. Comparación de grupos. Modelos de variable latente. Formulación gráfica. Análisis de sensibilidad.

    El enfoque multinivel: modelos jerárquicos. Modelo beta-binomial jerárquico. Shrinkage de parámetros. Variación en el intercepto. Variación en la pendiente. Pooling de estimaciones. Problemas de estimación.
