---
title: "Repaso de Variables Aleatorias"
bibliography: ../references.bib
---

* Variables aleatorias
    * Discretas
    * Continuas
* CDF
* PDF
* Distribucion conjunta
* Distribucion marginal
* Distribucion condicional
* Independencia e independencia condicional
* Momentos de una distribucion
* Regla de Bayes
* Distribuciones de probabilidad frecuentemente utilizadas
* Transformacion de variables aleatorias
    * Propiedades de transformaciones lineales

Este listado esta sacado del capitulo 2 de @Murphy2022

Tambien hay cosas interesantes en capitulo 3 de @Murphy2022

* Uncorrelated does not imply independent
* Correlation does not imply causation


1.  Pairwise independence does not imply mutual independence

    We say that two random variables are pairwise independent if 
    $p(X_2|X_1) = p(X_2)$ and hence $p(X_2, X_1) = p(X_1)p(X_2|X_1) = p(X_1)p(X_2)$

    We say that $n$ random variables are mutually independent if 
    $p(Xi|XS) = p(Xi)$ $\forall S \subseteq \{1, \cdots , n\}$ 
    and hence $\displaystyle p(X_{1:n}) = \prod_{i=1}^{n} p(X_i)$

    Show that pairwise independence between all pairs of variables does not necessarily 
    imply mutual independence. It suffices to give a counter example.

1.  Exercise 2.5 @Murphy2022
1.  Exercise 2.6 @Murphy2022

1. Exercise 3.5 [Gaussian vs jointly Gaussian ]