---
title: "Práctica - Unidad 3"
bibliography: ../references.bib
nocite: |
    @Martin2021, @Downey2021
pdf_file: https://github.com/estadisticaunr/estadistica-bayesiana/raw/pdf/practica/practica_03.pdf
---

::: {.content-visible when-format="html"}

[Descargar PDF]({{< meta pdf_file >}})

:::

## Métodos Computacionales

1.  Sea $X \sim \text{Normal}(\mu=3, \sigma=1.2)$. 
    i. Elabore un gráfico que permita visualizar la función de densidad de probabilidad 
    de $X$.
    i. ¿Cuál es la probabilidad de que $X$ sea menor a 2.5?
    i. ¿Cuál es la probabilidad de que $X$ sea mayor a 4?
    i. ¿Cuál es la probabilidad de que $X$ sea mayor 2 y menor 3?

1.  Sea $X \sim \text{Beta}(\alpha=10, \beta=2)$
    i. Elabore un gráfico que permita visualizar la función de densidad de probabilidad 
    de $X$.
    i. ¿Cuál es la probabilidad de que $X$ sea menor a 0.5?
    i. ¿Cuál es la probabilidad de que $X$ sea mayor a 0.8?
    i. ¿Cuál es la probabilidad de que $X$ sea mayor 0.25 y menor 0.75?

1.  Responda los dos puntos anteriores sin evaluar la función de densidad ni la función
    de distribución de las variables aleatorias mencionadas. Para eso genere muestras
    que provengan de las correspondientes distribuciones y utilícelas para responder las 
    preguntas mencionadas. Reflexione sobre las ventajas y desventajas de utilizar un 
    enfoque basado en la simulación para resolver problemas.

1.  En la Copa del Mundo de la FIFA 2014, Alemania jugó contra Brasil en la semifinal. 
    Los alemanes hicieron el primer gol a los 11 minutos y el segundo a los 23.
    Asuma que el tiempo entre goles sigue una distribución exponencial. Elija una distribución _a priori_ para el tiempo entre goles (puede ser conjugada o no).
    En ese momento del partido,

    i. ¿Cuál es la distribución _a posteriori_ del tiempo entre goles de Alemania?
    i. ¿Cuántos goles cabría esperar que Alemania hiciera al finalizar los 90 minutos?
    i. ¿Cuál era la probabilidad de que Alemania hiciera más de 5 goles (cosa que ocurrió)?
    <!-- http://allendowney.github.io/ThinkBayes2/chap08.html -->

1.  Grid approximation para una _skew-normal_. Estimar los parámetros $\xi$ (posición), $\omega$ (escala) y $\alpha$ (asimetría).
    $$
    f(x) = \frac{2}{\omega} \phi\left(\frac{x-\xi}{\omega}\right)\Phi\left( \alpha \frac{x-\xi}{\omega} \right)
    $$
    <!-- https://en.wikipedia.org/wiki/Skew_normal_distribution -->
    
    


1.  [Este tuit](https://twitter.com/pgroisma/status/1616137795180822528) propone un
    problema muy interesante. Una urna contiene una bola azul y una amarilla. 
    Se elije una bola al azar y se la vuelve a colocar junto con otra bola adicional 
    del mismo color. Se repite este proceso indefinidamente. 
    ¿Qué ocurre con la proporción de bolas azules en la urna a medida que 
    repetimos más y más veces?

    i. Tiende a 1/2
    i. Tiende a 0 ó a 1
    i. No se estabiliza
    i. Ninguna de las anteriores

    Escriba un programa en `R` para responder esta pregunta utilizando simulaciones.
    Genere gráficos que faciliten la comprensión del resultado.