---
title: "Práctica - Unidad 4"
bibliography: ../references.bib
nocite: |
    @Martin2021, @Downey2021, @Gelman2021, @Johnson2021
pdf_file: https://github.com/estadisticaunr/estadistica-bayesiana/raw/pdf/practica/practica_04.pdf
---

::: {.content-visible when-format="html"}

[Descargar PDF]({{< meta pdf_file >}})

:::

## Regresión


1.  **Mi primer regresión bayesiana**

    El conjunto de datos `sales` contiene los montos de inversión en publicidad y de 
    ingresos de una determinada compañía, por semana. Considere el siguiente modelo
    de regresión lineal simple:

    $$
    \begin{aligned}
    \text{ventas}_i &= \beta_0 + \beta_1 \text{publicidad}_i + \varepsilon_i \\
    \varepsilon_i &\underset{iid}{\sim} \text{Normal}(0, \sigma^2)
    \end{aligned}
    $$

    i. Ajuste el modelo utilizando `{brms}` y sus _priors_ por defecto.
    i. Construya un gráfico que muestre las ventas en función de la inversión en 
    publicidad y superponga la recta de regresión estimada.

1.  **Mejorando mi regresión bayesiana**

    Considere la siguiente versión del modelo del ejercicio anterior que propone 
    distribuciones _a priori_ para los parámetros del modelo:
    $$
    \begin{aligned}
    \text{ventas}_i &= \beta_0 + \beta_1 \text{publicidad}_i + \varepsilon_i \\
    \varepsilon_i &\underset{iid}{\sim} \text{Normal}(0, \sigma^2) \\
    \beta_0 &\sim \text{Normal}(\overline{\text{ventas}}, 10) \\
    \beta_1 &\sim \text{Normal}(0, 0.5) \\
    \sigma^2 &\sim \text{HalfNormal}(5)
    \end{aligned}
    $$

    i. Ajuste el modelo utilizando `{brms}` y los _priors_ sugeridos.
    i. Construya un gráfico que muestre las ventas en función de la inversión en 
    publicidad, superponga la recta de regresión estimada, y el intervalo de credibilidad
    del 95% para la recta de regresión.

1.  **Comparando de `lm()` y `brm()`**

    Utilice datos simulados para comparar la estimación por mínimos cuadrados con la 
    estimación Bayesiana en modelos de regresión.

    i. Simule 100 observaciones del modelo $Y = 2 + 3X + \varepsilon$ donde los valores 
    del predictor $X$ se obtienen de una distribución $\text{Uniforme}(0, 20)$ y los errores
    son obtenidos de manera independiente de una distribución $\text{Normal}(0, 5^2)$.
    i. Ajuste el modelo de regresión utilizando `lm()` y `brm()` del paquete `{brms}`
    utilizando _priors_ por defecto.
    i. Verifique que ambos métodos arrojan resultados similares.
    i. Represente gráficamente los datos y las dos rectas de regresión.
    i. Intente repetir la simulación, pero esta vez cree las condiciones para que ambos
    enfoques den resultados diferentes.
    <!-- @Gelman2021 8.8 -->

1.  **La altura... ¿se hereda?**

    El conjunto de datos de las alturas (`heights`) contiene las alturas de 5524 
    pares de madres e hijas en pulgadas registradas en un estudio realizado por Karl 
    Pearson y Alice Lee en 1903.

    i. Elabore un gráfico que permita ver la relación entre las alturas de las madres y 
    las hijas. Aplique las técnicas que crea necesaria para obtener una visualización 
    informativa y fidedigna.
    i. ¿Por qué es adecuado utilizar un modelo de regresión lineal?
    i. Ajuste el siguiente modelo de regresión lineal utilizando `{brms}` y _priors_ por
    defecto:

    $$
    \begin{aligned}
    \text{altura\_hija}_i &= \beta_0 + \beta_1 \text{altura\_madre}_i + \varepsilon_i \\
    \varepsilon_i &\underset{iid}{\sim} \text{Normal}(0, \sigma^2)
    \end{aligned}
    $$
    
    i. Calcule la media, el desvío estándar y el intervalo de credibilidad del 95% 
    para los parámetros del modelo utilizando el _posterior_.
    i. Interprete los coeficientes del modelo.
    i. Superponga la recta de regresión en el gráfico donde se visualiza la relación
    entre las variables.
    i. Obtenga el _posterior_ del peso medio de una hija cuya madre mide 58 pulgadas.
    <!-- @Gelman2021 Capitulo 6-->

1.  **Clima en Australia**

    El conjunto de datos `weather_WU` contiene 100 días de datos climáticos para dos 
    ciudades de Australia: Uluru y Wollongong. Se intentará predecir la temperatura a las
    3 de la tarde, utilizando otras variables.
    
    Considere los siguientes cuatro modelos:
    
    * $m_1$: `temp3pm ~ temp9am`
    * $m_2$: `temp3pm ~ location`
    * $m_3$: `temp3pm ~ temp9am + location`
    * $m_4$: `temp3pm ~ .`
    
    i. Ajuste cada uno de los modelos y construya gráficas para mostrar los parámetros obtenidos
    i. Realice pruebas predictivas _a posteriori_ para comparar los modelos
    i. Compare los ELPD de cada modelo utilizando LOO
    <!-- Bayes Rules. Capítulo 11. -->
    
1.  **Pingüinos**

    Considere el dataset de pingüinos de Palmer (`penguins`) y los siguientes 
    modelos:
        
    * $m_1$: `body_mass_g ~ flipper_length_mm`
    * $m_2$: `body_mass_g ~ species`
    * $m_3$: `body_mass_g ~ flipper_length_mm + species`
    * $m_4$: `body_mass_g ~ flipper_length_mm + species + flipper_length_mm:species`
    * $m_5$: `body_mass_g ~ flipper_length_mm + bill_length_mm + bill_depth_mm`
    
    i. Ajuste cada uno de los modelos y construya gráficas para mostrar los parámetros 
    obtenidos
    i. Realice pruebas predictivas _a posteriori_ para comparar los modelos
    i. Compare los ELPD de cada modelo utilizando LOO
    <!-- Bayes Rules. Capítulo 11. -->
    
1.  **De tal palo...**

    El dataset `child_iq` contiene información de los resultados de tests de coeficiente
    intelectual de niños de 3 años, educación de la madre, y edad de la madre cuando dio
    a luz.
    
    i. Ajuste un modelo de regresión del puntaje del bebé a los 3 años en función de la 
    edad de la madre
    i. Considere ahora un modelo que incluya la educación de la madre
    
1.  **Belleza**

    Hamermesh y Parker estudiaron la relación entre los resultados de los estudiantes en un 
    curso y la belleza de los instructores. La determinación de la belleza se hizo a 
    partir de las opiniones de seis estudiantes que no participaron de los cursos y no
    conocían las notas. Los datos se encuentran en el archivo `beauty`.
    
    i. Considere un modelo de regresión `courseevaluation ~ btystdave`
    
1.  **Ingresos**

    El dataset `earnings` contiene los resultados de la encuesta realizada por Ross sobre
    Trabajo, Familia y Bienestar.
    
    i. Ajuste un modelo que prediga ingreso en función de altura. ¿Qué transformación 
    sería necesaria para interpretar el intercepto como el ingreso promedio de una 
    persona con altura promedio?
    
1.  **!Kung**

    Los !Kung son un pueblo que habita en el desierto de Kalahari entre Botsuana, 
    Namibia y Angola. Hablan la lengua !Kung, que se destaca por su amplio uso de 
    consonantes clic (chasquido consonántico). El !K del nombre ǃKung es un sonido
    como cuando sale un corcho de una botella.
    
    El archivo `Howell1` contiene datos de un censo parcial realizado por Dobe Howell
    acerca de la población !Kung.
    
    Considere un modelo de altura en función del peso.
    
    i. Determine e interprete las distribuciones _a posteriori_ de los parámetros
    i. Construya un gráfico de altura en función del peso, incluya las observaciones
    de los individuos, la recta de regresión MAP, el intervalo del 80\% para la media y
    y el intervalo del 80\% para la altura predicha.
    i. Realice predicciones para individuos cuyos pesos son: 46.95, 43.72, 64.78, 32.59
    y 54.63. Calcule la altura esperada y el intervalo del 89\%.
    
1.  **Zorros**

    Considere del conjunto de datos sobre zorros urbanos (`foxes`). Ajuste tres modelos:

    * $m_1$: `weight ~ area`
    * $m_2$: `weight ~ groupsize`
    * $m_3$: `weight ~ area + groupsize`
    
    i. Para los modelos $m_1$ y $m_2$, represente gráficamente los resultados, incluyendo
    la recta de regresión MAP, su intervalo del 89\% y el intervalo de predicción del 89\%.
    ¿Es alguna de las dos variables importantes para predecir la masa de un zorro?
    i. Representar gráficamente las predicciones del modelo para cada predictor, dejando
    el otro constante en su valor medio. ¿Qué puede decirse sobre la importancia de las
    variables para predecir la masa de un zorro?

1.  **Un _prior_ informativo marca la diferencia**

    Considere el conjunto de datos sobre belleza y proporción de sexos (`sexratio`) .
    Estos datos provienen de un estudio de adolescentes estadounidenses cuyo atractivo en
    una escala de cinco puntos fue evaluado por entrevistadores en una 
    encuesta cara a cara. Años más tarde, muchos de estos encuestados tuvieron hijos
    y se registraron ciertos atributos entre los cuales se incluyó el sexo. 
    El objetivo del análisis es comparar la proporción de sexos de los hijos según la 
    belleza de los padres. Para ello considere el siguiente modelo de regresión:

    $$
    \begin{aligned}
    \text{pf}_i &= \beta_0 + \beta_1 \text{belleza}_i + \varepsilon_i \\
    \varepsilon_i &\underset{iid}{\sim} \text{Normal}(0, \sigma^2)
    \end{aligned}
    $$

    Donde $\text{pf}$ representa la proporción de bebés de sexo femenino y $\text{belleza}$
    representa el grupo de belleza de los padres.

    i. Ajuste el modelo utilizando mínimos cuadrados.
    i. Ajuste el modelo con `brm()` y sus _priors_ por defecto.
    i. Compare el ajuste de ambos modelos.
    i. Explore los _priors_ utilizados por `{brms}` y la distribución predictiva _a priori_.
    ¿Qué puede concluir? 
    i. Proponga distribuciones _a priori_ informativas.
    i. Ajuste el modelo utilizando `brm()` y los _priors_ informativos.
    i. Compare el resultado con los obtenidos anteriormente y concluya.

1.  **¡A la pesca de _priors_!**

    El conjunto de datos `fish-market` contiene mediciones morfológicas realizadas sobre
    pescados de diferentes especies. El objetivo es construir un modelo de regresión
    lineal que permita predecir el peso de los pescados en base a sus otros atributos. 
    
    Uno de los modelos propuestos es el siguiente:

    $$
    \begin{aligned}
    \log(\text{Weight}_i) &\sim \text{Normal}(\mu_i, \sigma) \\
    \mu_i  &= \beta_{0, j[i]} + \beta_{1, j[i]} \log(\text{Length1}_i)
    \end{aligned}
    $$

    $\text{Weight}_i$ es el peso del i-ésimo pescado en gramos y $\text{Length1}_i$ es la
    longitud del i-ésimo pescado en centímetros. La letra $j$ indexa las especies
    de los pescados. Por lo tanto, en este modelo cada especie tiene su propio intercepto
    y pendiente.

    i. Implemente el modelo utilizando `{brms}` y los siguientes _priors_ no informativos
    $$
    \begin{aligned}
    \beta_{0, j[i]} &\sim \text{Normal}(0, 10) \\
    \beta_{1, j[i]} &\sim \text{Normal}(0, 5)
    \end{aligned}
    $$
    i. Obtenga y visualice la distribución predictiva a _priori_.
    i. Elabore un gráfico y describa la función de densidad _a priori_ de los parámetros 
    $\beta_{0, j[i]}$ y  $\beta_{1, j[i]}$.
    i. Proponga _priors_ más adecuados en base a la interpretación de los parámetros del
    modelo y la información que tenga del problema.
    i. Nuevamente, obtenga y visualice la distribución predictiva a _priori_ y compare 
    con el resultado obtenido anteriormente.
    i. Ajuste el modelo, obtenga la distribución predictiva _a posteriori_ y grafíquela.
    
1.  **En búsqueda del modelo adecuado**

    Continuando con los datos del ejercicio anterior, El objetivo es construir un modelo 
    de regresión lineal que permita predecir el peso de los pescados en base a sus otros 
    atributos.

    Considere los siguientes modelos

    * $m_1$: `log(Weight) ~ 0 + Species`
    * $m_2$: `log(Weight) ~ 0 + Species + log(Length1)`
    * $m_3$: `log(Weight) ~ 0 + Species + log(Length1):Species`
    * $m_4$: `log(Weight) ~ 0 + Species + log(Length1):Species + log(Height)`
    * $m_5$: `log(Weight) ~ 0 + Species + log(Length1):Species + log(Height):Species`
    
    i. Ajuste cada uno de los modelos.
    i. Estime el ELPD de cada modelo utilizando LOO y seleccione el modelo más
    adecuado de acuerdo a este criterio.
    i. Explique el resultado.

1.  **Ejercicio donde haya sobre-ajuste**

    Idea: Utilizar priors estrechos para prevenir sobre-ajuste?

Lo que falta:

* Eleccion de distribuciones a priori
    * Priors de regularizacion (e.g. cuando hay muchos predictores numéricos)
* Sobreajuste y subajuste


<!-- 
Unidad 4: Modelos Lineales
Modelos lineales. Elección de distribuciones a priori. Regularización. Diagnóstico de modelos. Predicciones basadas en distribuciones de probabilidad. Pruebas predictivas a priori y a posteriori. Densidad predictiva a posteriori logarítmica evaluada punto a punto (lppd). Deviance. Criterios de información: AIC, BIC, WAIC. Validacion cruzada. Sobreajuste y subajuste. Validación cruzada utilizando muestreo por importancia mediante suavizado Pareto (PSIS-CV). 
-->